/**
 * First version of each browser with unflagged support, from caniuse-lite 1.0.30001809.
 *
 * Generated by scripts/capture-compat.mjs — do not edit by hand.
 *
 * A range such as `13.4-13.7` is caniuse's own notation for versions it does
 * not track separately; the audit reads the low end, which is the first release
 * known to support the feature. A browser missing from an entry has no version
 * that supports it.
 */
export const FEATURE_SUPPORT = {
  /** CSS math functions min(), max() and clamp() */
  'css-math-functions': {
    chrome: '79',
    edge: '79',
    safari: '13.1',
    firefox: '75',
    ios_saf: '13.4-13.7',
    samsung: '12.0',
  },
  /** Viewport units: vw, vh, vmin, vmax */
  'viewport-units': {
    chrome: '26',
    edge: '16',
    safari: '6.1',
    firefox: '19',
    ios_saf: '8',
    samsung: '4',
  },
  /** Small, Large, and Dynamic viewport units */
  'viewport-unit-variants': {
    chrome: '108',
    edge: '108',
    safari: '15.4',
    firefox: '101',
    ios_saf: '15.4',
    samsung: '21',
  },
  /** CSS Container Query Units */
  'css-container-query-units': {
    chrome: '105',
    edge: '105',
    safari: '16.0',
    firefox: '110',
    ios_saf: '16.0',
    samsung: '20',
  },
  /** CSS Container Queries (Size) */
  'css-container-queries': {
    chrome: '106',
    edge: '106',
    safari: '16.0',
    firefox: '110',
    ios_saf: '16.0',
    samsung: '20',
  },
  /** CSS Cascade Layers */
  'css-cascade-layers': {
    chrome: '99',
    edge: '99',
    safari: '15.4',
    firefox: '97',
    ios_saf: '15.4',
    samsung: '18.0',
  },
  /** CSS Environment Variables env() */
  'css-env-function': {
    chrome: '69',
    edge: '79',
    safari: '11.1',
    firefox: '65',
    ios_saf: '11.3-11.4',
    samsung: '10.1',
  },
  /** :is() CSS pseudo-class */
  'css-matches-pseudo': {
    chrome: '88',
    edge: '88',
    safari: '14',
    firefox: '78',
    ios_saf: '14.0-14.4',
    samsung: '15.0',
  },
  /** :has() CSS relational pseudo-class */
  'css-has': {
    chrome: '105',
    edge: '105',
    safari: '15.4',
    firefox: '121',
    ios_saf: '15.4',
    samsung: '20',
  },
  /** CSS Variables (Custom Properties) */
  'css-variables': {
    chrome: '49',
    edge: '16',
    safari: '10',
    firefox: '31',
    ios_saf: '10.0-10.2',
    samsung: '5.0-5.4',
  },
  /** CSS Logical Properties */
  'css-logical-props': {
    chrome: '89',
    edge: '89',
    safari: '15',
    firefox: '66',
    ios_saf: '15.0-15.1',
    samsung: '15.0',
  },
  /** CSS Nesting */
  'css-nesting': {
    chrome: '120',
    edge: '120',
    safari: '17.2',
    firefox: '117',
    ios_saf: '17.2',
    samsung: '25',
  },
} as const

export type CaniuseFeatureId = keyof typeof FEATURE_SUPPORT
