/**
 * Regenerates `src/core/compat-data.ts` from caniuse-lite.
 *
 * The numbers are baked into the package rather than looked up at run time,
 * which is only defensible because of what they are: the first version of each
 * browser that shipped a feature is a historical fact and does not move. What
 * does move is how many people still run that version — and that number is
 * deliberately absent here, because it belongs to the project being compiled,
 * not to this compiler. Bring your own `browserslist` and the audit will tell
 * you which of your targets falls short.
 *
 * caniuse-lite is therefore a devDependency: it produces this file and then has
 * no further part in anything the package ships.
 *
 *   node scripts/capture-compat.mjs
 */
import { createRequire } from 'node:module'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const caniuse = require('caniuse-lite')

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'core',
  'compat-data.ts',
)

/**
 * Browsers with a version history worth comparing against.
 *
 * The evergreen mobile entries caniuse carries — `and_chr`, `and_ff`, `op_mob`
 * — publish a single row holding whatever version is current, so a "minimum
 * supported version" for them would be a number that says nothing. Android
 * WebViews are covered by `chrome`, which is what they are.
 */
const BROWSERS = ['chrome', 'edge', 'safari', 'firefox', 'ios_saf', 'samsung']

/**
 * Every caniuse entry this compiler's output depends on.
 *
 * Exactly the entries `COMPAT_FEATURES` names in its `source` fields — nothing
 * captured "in case it is useful later". Support data that nothing reads is
 * data nobody notices going stale.
 */
const FEATURES = [
  'css-math-functions',
  'viewport-units',
  'viewport-unit-variants',
  'css-container-query-units',
  'css-container-queries',
  'css-cascade-layers',
  'css-env-function',
  'css-matches-pseudo',
  'css-has',
  'css-variables',
  'css-logical-props',
  'css-nesting',
]

/**
 * The earliest version from which support never lapses again.
 *
 * Scanning to the end rather than stopping at the first `y` matters: a feature
 * that shipped, regressed, and returned would otherwise report the version
 * before the regression, which is the one number that is not safe to quote.
 * Version order comes from the agent record, because the stats object is keyed
 * by version string and JavaScript hoists the integer-like keys.
 */
function firstStableVersion(feature, browser) {
  const stats = feature.stats[browser]
  const agent = caniuse.agents[browser]
  if (!stats || !agent) return null
  let candidate = null
  for (const version of agent.versions) {
    if (!version) continue
    const support = stats[version]
    if (support === undefined) continue
    if (/^y/.test(support)) {
      if (candidate === null) candidate = version
    } else {
      candidate = null
    }
  }
  return candidate
}

const rows = []
for (const id of FEATURES) {
  const feature = caniuse.feature(require(`caniuse-lite/data/features/${id}`))
  const entries = BROWSERS.map((browser) => [
    browser,
    firstStableVersion(feature, browser),
  ]).filter(([, version]) => version !== null)
  const support = entries
    .map(([browser, version]) => `    ${browser}: '${version}',`)
    .join('\n')
  rows.push(
    `  /** ${feature.title} */\n  '${id}': {\n${support}\n  },`,
  )
}

const version = require('caniuse-lite/package.json').version
writeFileSync(
  OUT,
  `/**
 * First version of each browser with unflagged support, from caniuse-lite ${version}.
 *
 * Generated by scripts/capture-compat.mjs — do not edit by hand.
 *
 * A range such as \`13.4-13.7\` is caniuse's own notation for versions it does
 * not track separately; the audit reads the low end, which is the first release
 * known to support the feature. A browser missing from an entry has no version
 * that supports it.
 */
export const FEATURE_SUPPORT = {
${rows.join('\n')}
} as const

export type CaniuseFeatureId = keyof typeof FEATURE_SUPPORT
`,
  'utf8',
)
console.log(`compat-data.ts  <-  caniuse-lite ${version}`)
