/**
 * Reshapes the CommonJS build so that both halves of it — the code and the
 * declarations — describe a module you can call.
 *
 * Neither step can live in `tsup.config.ts`. `onSuccess` fires when the
 * JavaScript build finishes, while declarations are generated by a separate
 * worker that lands afterwards, so a rewrite of `index.d.cts` from there is
 * silently overwritten by the file it was meant to change. Running as a
 * discrete step after `tsup` exits removes the race instead of racing better.
 *
 * Both steps are idempotent: `npm run build` is run repeatedly and often
 * interrupted, and a post-processing step that corrupts the output on its
 * second run is worse than none.
 */
import { readFile, writeFile } from 'node:fs/promises'

const JS_PATH = 'dist/index.cjs'
const TYPES_PATH = 'dist/index.d.cts'

/**
 * Makes `module.exports` the plugin itself rather than an object holding it
 * under `.default`.
 *
 * Every `postcss.config.js` in the wild is written
 * `plugins: [require('postcss-adaptive-matrix')({ ... })]`, and against an
 * exports object that throws "plugin is not a function" — the one call shape
 * most consumers reach for first. `Object.assign` keeps every named export
 * reachable as a property, `.default` included, so both spellings work.
 *
 * tsup's own `cjsInterop` does not cover this: it applies only when the entry
 * has a lone default export, and this one also exports helpers by name. An
 * esbuild `footer` does not work either — tsup appends its `exports.x = x`
 * lines after it, so the line would run before `default` had been assigned and
 * quietly do nothing.
 */
const MARKER = '/* callable module.exports */'
const CJS_DEFAULT_EXPORT =
  `\n${MARKER}\nif (module.exports.default) ` +
  'module.exports = Object.assign(module.exports.default, module.exports);\n'

async function makeCjsCallable(): Promise<void> {
  const source = await readFile(JS_PATH, 'utf8')
  if (source.includes(MARKER)) return
  await writeFile(JS_PATH, source + CJS_DEFAULT_EXPORT, 'utf8')
}

/**
 * Restates the CJS declarations as `export =`, so the types describe the module
 * that is actually shipped.
 *
 * Without this the `.d.cts` contradicts the code above, and a TypeScript
 * consumer writing the very line the docs recommend —
 * `import adaptiveMatrix = require('postcss-adaptive-matrix')` — is told the
 * expression has no call signatures. Working code, red squiggles: the worse of
 * the two failures, because the compiler is the thing people believe.
 *
 * `export =` is the only way to type a callable module and cannot coexist with
 * other export statements, so the generated `export { ... }` is rewritten
 * rather than added to. Values become properties on the callable; types move
 * into a namespace merged with it, which keeps both `lib.AdaptiveMatrixOptions`
 * and `import type { AdaptiveMatrixOptions } from '...'` resolving.
 *
 * Rewriting generated output is only safe if it fails loudly, so every
 * assumption here throws rather than guessing.
 */
async function declareCjsCallable(): Promise<void> {
  const source = await readFile(TYPES_PATH, 'utf8')
  if (source.includes('export = _cjs')) return

  const statement = /export \{([^{}]*)\};?\s*$/.exec(source)
  if (!statement) throw new Error(`${TYPES_PATH}: no trailing export statement to rewrite`)

  const types: string[] = []
  const values = new Map<string, string>()
  let callable: string | undefined
  for (const entry of statement[1]!.split(',').map((part) => part.trim())) {
    if (!entry) continue
    if (entry.startsWith('type ')) {
      types.push(entry)
      continue
    }
    const parts = entry.split(/\s+as\s+/)
    if (parts.length > 2) throw new Error(`${TYPES_PATH}: cannot read export "${entry}"`)
    const local = parts[0]!
    const exported = parts[1] ?? local
    if (exported === 'default') callable = local
    values.set(exported, local)
  }
  if (!callable) throw new Error(`${TYPES_PATH}: no default export to make callable`)

  const properties = [...values]
    .map(([exported, local]) => `  ${exported}: typeof ${local};`)
    .join('\n')
  const namespace = types.length
    ? `declare namespace _cjs {\n  export { ${types.join(', ')} };\n}\n`
    : ''

  await writeFile(
    TYPES_PATH,
    source.slice(0, statement.index) +
      `declare const _cjs: typeof ${callable} & {\n${properties}\n};\n` +
      namespace +
      'export = _cjs;\n',
    'utf8',
  )
}

await makeCjsCallable()
await declareCjsCallable()
